# Graph's vertices Configurations
vertices:
  N: 4 # number of vertices in graph (from 1 to N)
  objects: # place objects in a vertex. Format: 'ID,OBJECT'
    - '0,K' # Vertex 1, contains amphibian kit
    - '1,P1' # Vertex 2, contains 1 person to be rescued
    - '3,P2,K' # Vertex 4, contains 2 persons to  be rescued and an amphibian kit

# Graph's edges Configurations
edges: # 'A,B,W,F?'. Example - '1,2,1,F' = Edge between vertices 1 and 2, with weight 1 and it is flooded (flooded is optional)
  - '0,1,1,F'
  - '2,3,1'
  - '1,2,1'
  - '0,2,4'
  - '1,3,5'

# Time Constraints Definitions
action_duration:
  unequip: 1 # takes x time units to unequip
  equip: 2 # takes x time units to equip
  amphibian: 3 # moving with amphibian kit is x times slower

agents: # 'type, ID, initial_position' (Types can be: human, stupid-greedy, etc.)
  - 'human,1,2'
#  - 'stupid-greedy,2,0'
#  - 'stupid-greedy,3,3'