# Graph's vertices configurations
vertices:
  N: 15           # vertices 0..3
  objects:
    - '0,K'      # amphibian kit
    - '4,K'
    - '9,K'

    - '6,P2'     # rescue targets
    - '8,P3'
    - '11,P1'
    - '13,P2'
    - '14,P3'

# Graph's edges configurations
edges:
  # Format: 'A,B,W,F?'  (F is optional 'F' for flooded)
  # Main backbone
  - '0,1,1'
  - '1,2,1'
  - '2,3,1'
  - '3,4,1'
  - '4,5,1'
  - '5,6,1'
  - '6,7,1'
  - '7,8,1'
  - '8,9,1'
  - '9,10,1'
  - '10,11,1'
  - '11,12,1'
  - '12,13,1'
  - '13,14,1'

  # Inner connections (non-flooded)
  - '1,4,1'
  - '2,5,1'
  - '3,6,1'
  - '5,8,1'
  - '7,10,1'
  - '9,12,1'
  - '10,13,1'

  # Flooded shortcuts (high strategic value)
  - '0,3,1,F'
  - '2,7,1,F'
  - '4,9,1,F'
  - '6,11,1,F'
  - '8,13,1,F'
  - '5,12,1,F'

# Time constraints definitions
action_duration:
  unequip: 1     # takes 1 time unit to unequip
  equip: 1       # takes 2 time units to equip
  amphibian: 1   # moving with amphibian kit is 3x slower

agents: # 'type, initial_position' (Types can be: human, stupid-greedy, etc.)
  - 'minimax,1'
  - 'minimax,10'