# Number of vertices in the graph (0 ... N-1)
vertices:
  N: 4

# Graph edges
# Format: 'u,v,weight,p'
# p = probability that the edge is flooded
edges:
  - '0,1,1,0.1'
  - '1,2,1,0.2'
  - '2,3,1,0.3'
  - '0,3,3,0.4'

# Start and target vertices
start: 0
target: 3