# Graph's vertices configurations
vertices:
  N: 4           # vertices 0..3
  objects:
    - '0,K'      # vertex 0: amphibian kit
    - '3,P3'     # vertex 3: 3 people to rescue

# Graph's edges configurations
edges:
  # Format: 'A,B,W,F?'  (F is optional 'F' for flooded)
  - '0,3,1,F'    # flooded shortcut: 0 <-> 3, weight 2, FLOODED
  - '0,1,1'      # dry path edges
  - '1,2,1'
  - '2,3,1'

# Time constraints definitions
action_duration:
  unequip: 1     # takes 1 time unit to unequip
  equip: 1       # takes 2 time units to equip
  amphibian: 1   # moving with amphibian kit is 3x slower

agents: # 'type, initial_position' (Types can be: human, stupid-greedy, etc.)
  - 'minimax,0'
  - 'minimax,2'